#!/usr/bin/with-contenv bash
# shellcheck shell=bash

#!/usr/bin/with-contenv bash
exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 2812" \
        s6-setuidgid abc /usr/bin/monit -I -B -c /config/monitrc
