name: Build Image On Release

on:
  release:
    types: [ published ]

jobs:
  call-workflow:
    uses: linuxserver-labs/docker-actions/.github/workflows/build-image.yml@v5
    with:
      repo_owner: ${{ github.repository_owner }}
      app_name: "monit"
      release_type: "alpine"
      release_url: "v3.15/main"
      release_name: "monit"
    secrets:
      scarf_token: ${{ secrets.SCARF_TOKEN }}