name: Build Image On Release

on:
  release:
    types: [ published ]

jobs:
  call-workflow:
    uses: linuxserver-labs/docker-actions/.github/workflows/build-image.yml@v1
    with:
      repo_owner: ${{ github.repository_owner }}
      app_name: "monit"
