name: Build Image On Release

on:
  release:
    types: [ published ]
  pull_request:
  workflow_dispatch:

jobs:
  call-workflow:
    uses: linuxserver-labs/docker-actions/.github/workflows/build-image.yml@v7
    with:
      repo_owner: ${{ github.repository_owner }}
      app_name: "monit"
      release_type: "alpine"
      release_url: "v3.19/main"
      release_name: "monit"
      target-arch: "64"
