name: Check for update and release

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'

jobs:
  call-workflow:
    uses: linuxserver-labs/docker-actions/.github/workflows/check-and-release.yml@v7.0.6
    with:
      repo_owner: ${{ github.repository_owner }}
      app_name: "monit"
      release_type: "alpine"
      release_url: "v3.20/main"
      release_name: "monit"
    secrets:
      repo_release_token: ${{ secrets.repo_release_token }}
