#!/usr/bin/with-contenv bash

#Copy defaults
if [ ! -f "/config/monitrc" ]; then
	cp -a /defaults/monitrc /config/monitrc
fi

if [ ! -f "/config/monit2apprise.sh" ]; then
	cp -a /defaults/monit2apprise.sh /config/monit2apprise.sh
fi

# set permissions
chmod 700 \
	/config/monitrc

chmod +x \
	/config/monit2apprise.sh

chown -R abc:abc \
	/config